server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:5001/eureka'
    healthcheck:
      enabled: true
      
spring:
  application:
    name: eureka-client-1